name: Deploy Backend

on:
  push:
    branches: ['master']
    paths: ['IT/codekatabattle/**/*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        working-directory: ./IT/codekatabattle
        run: mvn -B package --file pom.xml

      - name: Run tests
        working-directory: ./IT/codekatabattle
        run: mvn test
